name: kedaireka
description: A new Flutter project.

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  animated_bottom_navigation_bar: ^0.3.2
  auto_size_text: ^3.0.0
  cached_network_image: ^3.1.0+1
  camera: ^0.9.4+5
  carousel_slider: ^4.0.0
  cupertino_icons: ^1.0.2
  dio: ^4.0.3
  file_picker: ^4.2.2+1
  flutter:
    sdk: flutter
  flutter_easyloading: ^3.0.3
  flutter_native_splash: ^1.3.1
  flutter_spinkit: ^5.1.0
  flutter_svg: ^0.23.0+1
  get: ^4.3.8
  get_storage: ^2.0.3
  google_fonts: ^2.1.0
  http_parser: ^4.0.0
  image_picker: ^0.8.0
  loading_overlay: ^0.3.0
  mime: ^1.0.1
  path: ^1.8.0
  sentry_flutter: ^6.1.2

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec
# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/Logo Find Disease.svg
    - assets/images/image-welcometitle+layer.png
    - assets/accounts/icon-info-detail-rounded.png
    - assets/accounts/icon-logout-rounded.png
    - assets/accounts/icon-security-rounded.png
    - assets/button/button-close.png
    - assets/button/button-flash.png
    - assets/button/button-gallery.png
    - assets/instructions/Illustration - Center!.png
    - assets/instructions/Illustration - Focus.png
    - assets/instructions/Illustration - Notice!.png
    - assets/instructions/Illustration - Observe.png
    - assets/images/image-backgroundsplashscreen.png
    - assets/images/Logo Find Disease.png
    - assets/button/button-next-enabled.png
    - assets/button/button-previous-enabled.png
    - assets/button/Take Photo Button.png
  #   - images/a_dot_ham.jpeg
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
